# Read more https://github.com/actions/labeler

root:
  - changed-files:
      - any-glob-to-any-file: "*"

github:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - ".dockerignore"
          - "Dockerfile"

vscode:
  - changed-files:
      - any-glob-to-any-file: ".vscode/**"

md:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "**/*.mdx"

"d.ts":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.d.ts"

stories:
  - changed-files:
      - any-glob-to-any-file:
          - "storybook/**"
          - "**/*.stories.tsx"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"
          - "**/*.test.tsx"
          - "**/*.test.ts"
          - "**/*.spec.tsx"
          - "**/*.spec.ts"
